In [1]:
import numpy as np
import ROOT, glob, os, sys
import read_root_files as read
import matplotlib.pyplot as plt
import datetime
plt.ion()

Welcome to JupyROOT 6.17/01


In [2]:
path='/Users/kmulrey/LOFAR/LORA/LORAraw/'
path2='new_files/'


In [3]:
file_name='20200202_2304'

In [4]:
file=path2+file_name+'.npz'


In [5]:
d=np.load(file)
print d.files

['GPS_Time_Stamp', 'Peak_Height_Raw', 'Run_Id', 'Event_Id', 'Trigg_Threshold', 'Channel_Passed_Threshold', 'CTD', 'Charge_Corrected', 'nsec_Online', 'Peak_Height_Corrected', 'sigma_ovr_thresh', 'Detector', 'Waveform_Raw']


In [6]:
waveforms= d['Waveform_Raw']#[0]
det=d['Detector']
id=d['Event_Id']
gps=d['GPS_Time_Stamp']
ctd=d['CTD']
ns=d['nsec_Online']

In [10]:
n=len(gps)
print n

6648


In [11]:
print ctd

[1.98334256e+08 1.98334256e+08 1.98334256e+08 ... 1.81486505e+08
 1.81486842e+08 1.81486842e+08]


In [9]:
events,event_ind=np.unique(id,return_index=True)
nEvents=len(events)


In [33]:
def fill_stations(det, wf, lasa):
    
    print lasa,det, wf.shape
    det1=(lasa-1)*4+1
    det2=(lasa-1)*4+2
    det3=(lasa-1)*4+3
    det4=(lasa-1)*4+4
    
    #print 'relevant detectors'
    #print det1,det2,det3,det4
    nTrace=4000
    wf_1=np.empty([0,nTrace])
            

    if det1 in det:
        ind1=np.where(det==det1) 
        ind2=np.where(det==det2)
        ind3=np.where(det==det3)
        ind4=np.where(det==det4)
        print np.asarray(wf[ind1]).shape
        wf_1=np.concatenate((wf_1,np.asarray(wf[ind1])))
        wf_1=np.concatenate((wf_1,np.asarray(wf[ind2])))
        wf_1=np.concatenate((wf_1,np.asarray(wf[ind3])))
        wf_1=np.concatenate((wf_1,np.asarray(wf[ind4])))

         
    
    return wf_1

In [34]:
max_events=5000
count=0
import time
for e in np.arange(0,nEvents-1):
    if count<max_events:
        gps_pre=gps[id==id[event_ind[e-1]]]
        gps_post=gps[id==id[event_ind[e+1]]]

        gps_sub= gps[id==id[event_ind[e]]]
        nDet=len(det[id==id[event_ind[e]]])
        
        if nDet>11:
            count=count+1
            #if det[id==id[event_ind[e-1]]][0]==21 or det[id==id[event_ind[e-1]]][0]==37 or det[id==id[event_ind[e-1]]][0]==33:
            #    gps_pre[0]=gps_pre[0]-18
            #if det[id==id[event_ind[e+1]]][0]==21 or det[id==id[event_ind[e+1]]][0]==37 or det[id==id[event_ind[e+1]]][0]==33:
            #    gps_post[0]=gps_post[0]-18
            print ''

            print '.......................................................'    
            print ''
            print 'event before: {0}:  {1}'.format(int(id[event_ind[e-1]]),det[id==id[event_ind[e-1]]])
            print time.strftime("%H:%M:%S", time.gmtime(gps_pre[0]))
            #print ctd[id==id[event_ind[e-1]]]
            print ns[id==id[event_ind[e-1]]]

            print '_____ event {0} _____'.format(int(id[event_ind[e]]))
    
            print '{0} detectors:  {1}'.format(len(gps_sub), det[id==id[event_ind[e]]])
            for i in np.arange(1):
                print time.strftime("%H:%M:%S", time.gmtime(gps_sub[i]))
            #print ctd[id==id[event_ind[e]]]
            print ns[id==id[event_ind[e]]]


            print 'event after: {0}:  {1}'.format(int(id[event_ind[e+1]]),det[id==id[event_ind[e+1]]])
            print time.strftime("%H:%M:%S", time.gmtime(gps_post[0]))
            #print ctd[id==id[event_ind[e+1]]]
            print ns[id==id[event_ind[e+1]]]

            wf=waveforms[id==id[event_ind[e]]]
            det_event=det[id==id[event_ind[e]]]
            #print 'waveforms:     {0}'.format(wf.shape)
            
            stations=[]
        
            '''
            wf1=fill_stations(det_event, wf,1)
            wf2=fill_stations(det_event, wf,2)
            wf3=fill_stations(det_event, wf,3)
            wf4=fill_stations(det_event, wf,4)
            wf5=fill_stations(det_event, wf,5)
            wf6=fill_stations(det_event, wf,6)
            wf7=fill_stations(det_event, wf,7)
            wf8=fill_stations(det_event, wf,8)
            '''
            
        


.......................................................

event before: 212:  [ 9. 10. 11. 12.]
23:13:54
[6.43017417e+08 6.43017417e+08 6.43017418e+08 6.43017418e+08]
_____ event 213 _____
12 detectors:  [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
23:13:56
[5.49121096e+08 5.49121096e+08 5.49121091e+08 5.49121091e+08
 5.49121165e+08 5.49121165e+08 5.49121161e+08 5.49121161e+08
 5.49120927e+08 5.49120927e+08 5.49120928e+08 5.49120928e+08]
event after: 214:  [13. 14. 15. 16.]
23:14:00
[2.65266638e+08 2.65266638e+08 2.65266633e+08 2.65266633e+08]

.......................................................

event before: 381:  [ 9. 10. 11. 12.]
23:19:58
[3.29424976e+08 3.29424976e+08 3.29424970e+08 3.29424970e+08]
_____ event 382 _____
12 detectors:  [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
23:20:00
[83701351. 83701351. 83701351. 83701351. 83700904. 83700904. 83700901.
 83700901. 83700829. 83700829. 83700828. 83700828.]
event after: 383:  [21. 22. 23. 24.]
23:20:04
[23375194. 23